# Generated by Django 5.0.6 on 2026-08-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='session',
            new_name='sessions_se_start_t_a270d7_idx',
            old_name='sessions_se_start_t_idx',
        ),
    ]
